

ftp:
  host: localhost
  port: 11021
  user:
    name: user
    password: secret
  admin:
    name: admin
    password: secret
  passiveMode: true

flyway:
  url: "jdbc:h2:mem:camel_workshop;MODE=MySQL;INIT=RUNSCRIPT FROM 'classpath:flyway_init.sql'"
  user: sa
  password:
  baseline-on-migrate: true

spring:
  activemq:
    broker-url: tcp://localhost:61616
server:
  port: 9500
