
ftp:
  host: 192.168.2.66
  port: 21
  user:
    name: user
    password: secret
  admin:
    name: admin
    password: secret
  passiveMode: false

spring:
  activemq:
    broker-url: tcp://192.168.2.66:61616
